USE [CARE_6612];
GO

IF OBJECT_ID('DBO.STP_INSERT_AUDITLOG', 'P') IS NOT NULL
    DROP PROCEDURE DBO.STP_INSERT_AUDITLOG;
GO
CREATE PROCEDURE DBO.STP_INSERT_AUDITLOG
    @ACTION   VARCHAR(25),
    @STATUS   BIT = 0,
    @DETAILS  VARCHAR(200) = NULL,
	@_TIME DATETIME,
    @USERID   INT
AS
BEGIN
    SET NOCOUNT ON;

    INSERT INTO DBO.AUDITLOG (_ACTION, _STATUS, _TIME, DETAILS, USERID)
    VALUES (@ACTION, @STATUS, @_TIME, @DETAILS, @USERID);
END
GO

EXEC DBO.STP_INSERT_AUDITLOG 
    @ACTION = 'Login',
    @STATUS = 1,
    @_TIME = '2025-08-16 14:30:00',
    @DETAILS = 'Manual test insert',
    @USERID = 10;


