--TABLES till User Story 2082

use  [care_6612];
go

IF OBJECT_ID('DBO.ROLES','U') IS NULL
CREATE TABLE DBO.ROLES (
ID INT IDENTITY(1,1) PRIMARY KEY,
ROLENAME VARCHAR(50) NOT NULL

);
GO



IF OBJECT_ID('DBO.USERS','U') IS NULL
CREATE TABLE DBO.USERS (
	ID INT IDENTITY(1,1) PRIMARY KEY,
	FIRSTNAME VARCHAR(25) NOT NULL ,
	LASTNAME VARCHAR(25) NOT NULL ,
	USER_PASSWORD_HASHED VARBINARY(255) NOT NULL,
	USERADDRESS VARCHAR(255) NOT NULL,
	EMAIL VARCHAR(100) unique NOT NULL,
	PHONE_NO VARCHAR(25) NOT NULL,
	ROLEID INT NOT NULL,
	CONSTRAINT FK_USER_ROLE FOREIGN KEY (ROLEID) REFERENCES DBO.ROLES(ID)
);
GO



IF OBJECT_ID('DBO.AUDITLOG','U') IS NULL
CREATE TABLE DBO.AUDITLOG(
ID INT IDENTITY(1,1) PRIMARY KEY,
_ACTION VARCHAR(25) NOT NULL,
_STATUS BIT NOT NULL DEFAULT 0,
_TIME DATETIME ,
DETAILS VARCHAR(200),
USERID INT NOT NULL,
CONSTRAINT FK_AUDIT_USER FOREIGN KEY (USERID) REFERENCES  DBO.USERS(ID)
);
GO

IF OBJECT_ID('DBO.PATIENTS','U') IS NULL
CREATE TABLE DBO.PATIENTS(
ID INT IDENTITY(1,1) PRIMARY KEY,
FIRSTNAME VARCHAR(25) NOT NULL,
LASTNAME VARCHAR(25) NOT NULL,
GENDER VARCHAR(10) NOT NULL,
USERADDRESS VARCHAR(255) NOT NULL,
EMAIL VARCHAR(100) UNIQUE NOT NULL,
PHONENO VARCHAR(25) NOT NULL,
EMERGENCY_PHONE VARCHAR(20) NOT NULL
);
GO


