--STORED PROCEDURES FOR USERS TABLE
USE [care_6612];
GO


IF OBJECT_ID('DBO.STP_CREATE_USER','P') IS NOT NULL DROP PROCEDURE DBO.STP_CREATE_USER;
GO
CREATE PROCEDURE DBO.STP_CREATE_USER @FNAME VARCHAR(50),@LNAME VARCHAR(50),@USERPASSWORD VARCHAR(255),@USERADDRESS VARCHAR(255),@EMAIL VARCHAR(255),@PNO VARCHAR(25),@ROLEID INT
AS 
BEGIN 
     SET NOCOUNT ON;
	 INSERT INTO DBO.USERS(FIRSTNAME,LASTNAME,USER_PASSWORD_HASHED,USERADDRESS,EMAIL,PHONE_NO,ROLEID)
	 VALUES(@FNAME,@LNAME,HASHBYTES('SHA2_256', @USERPASSWORD),@USERADDRESS,@EMAIL,@PNO,@ROLEID);
	 
	 SELECT CAST(SCOPE_IDENTITY() AS INT) AS NEWID;
END
GO


IF OBJECT_ID('DBO.STP_FETCH_USER','P') IS NOT NULL DROP PROCEDURE DBO.STP_FETCH_USER;
GO
CREATE PROCEDURE DBO.STP_FETCH_USER @EMAIL VARCHAR(255),@USERPASSWORD VARCHAR(255)
AS 
BEGIN 
     SET NOCOUNT ON;

	 SELECT U.*, R.ROLENAME FROM DBO.USERS U INNER JOIN DBO.ROLES R ON R.ID = U. ROLEID 
	 WHERE U.EMAIL=@EMAIL AND U.USER_PASSWORD_HASHED=HASHBYTES('SHA2_256',@USERPASSWORD); 
END
GO


SELECT U.*, R.ROLENAME FROM DBO.USERS U INNER JOIN DBO.ROLES R ON R.ID = U. ROLEID 
WHERE U.EMAIL='noman@gmail.com' AND U.USER_PASSWORD_HASHED=HASHBYTES('SHA2_256','noman123');

update USERS 
set USER_PASSWORD_HASHED=HASHBYTES('SHA2_256','qarar123')
where firstname='qarar';


select * from AUDITLOG where Users.USER_PASSWORD_HASHED=HASHBYTES('SHA2_256','noman123');

EXEC STP_CREATE_USER 'ali','nawaz','ali123','lahore','ali@gmail.com','03180625268','7';
EXEC STP_FETCH_USER 'noman@gmail.com','noman123'
